### ISSUE TITLE
fit_and_plot: Error in socketConnection & Error in pdf (graphs/2020-ftrsgt-paper/...): cannot open file

### ISSUE THREAD

**Issue by victoris93** [ihrke/2020-ftrsgt-paper#1]
Hello Matthias,

I've been trying to run the analyses in RStudio for Mac and so for I've run into the following issues in `ordprobit_nested.R`.

1. `this.file.name()` throws the following error: ` Error in path.expand(path) : invalid 'path' argument `. `sys.frames()[[1]]$ofile` returns NULL. I went through the issue on stackoverflow you cite at the top of `notify_pushbullet.R` and as far I as understand, the function is supposed to yield the same result as `getwd()` which gives you the path to the project. Is that correct? When I replaced `this.file.name()` with `getwd()` in line 9 in `ordprobit_nested.R`, the output of `bname` is `[1] "2020-ftrsgt-paper"`. Is this the intended output?

2. When I get to model fitting at line 139 `models.fitted=pblapply(models.wrap, function(lmod){ fit_and_plot(lmod$mod.name, lmod$mod)}, cl=10)`,  I get the following errors for 14 out of 23 models: 
<img width="877" alt="Screenshot 2022-01-28 at 14 51 41" src="https://user-images.githubusercontent.com/49495286/151558525-a3083beb-83fe-42b7-aec4-7a17cd081cf8.png">
<img width="880" alt="Screenshot 2022-01-28 at 14 51 51" src="https://user-images.githubusercontent.com/49495286/151558536-88034269-0c1a-4595-bda8-e14ed1f2404d.png">

The execution also throws a warning:
<img width="819" alt="Screenshot 2022-01-28 at 14 54 14" src="https://user-images.githubusercontent.com/49495286/151558779-93639c02-7581-41ca-8008-3cfbf972489c.png">

Might this have something to do with the first issue? I have never used stan packages or parallel processing in R before, so I might be missing something obvious here.

Thanks in advance!

**Comment by ihrke** [comment]
replace that with
```
bname="ordprobit_nested"
```
